import Providers from '../app/provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import LoadingLogin from '@/components/home/loadingLogin';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pharmaceutitals',
  description: 'Generated by Johan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
        {children}
      </Providers>
    </body>
    </html>
  )
}
